config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sections
  resources :time_preferences
  resources :time_blocks
  resources :professors
  resources :course_preferences
  resources :courses
  resources :classrooms

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post "generate" => "static_pages#generate", as: :generate
  get "status" => "static_pages#status", as: :status

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/time_preference.rb
class TimePreference < ApplicationRecord
  belongs_to :professor
  belongs_to :time_block
end

app/controllers/time_preferences_controller.rb
class TimePreferencesController < ApplicationController
  before_action :set_time_preference, only: %i[ show edit update destroy ]

  # GET /time_preferences or /time_preferences.json
  def index
    @time_preferences = TimePreference.all
  end

  # GET /time_preferences/1 or /time_preferences/1.json
  def show
  end

  # GET /time_preferences/new
  def new
    @time_preference = TimePreference.new
  end

  # GET /time_preferences/1/edit
  def edit
  end

  # POST /time_preferences or /time_preferences.json
  def create
    @time_preference = TimePreference.new(time_preference_params)

    respond_to do |format|
      if @time_preference.save
        format.html { redirect_to time_preference_url(@time_preference), notice: "Time preference was successfully created." }
        format.json { render :show, status: :created, location: @time_preference }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_preferences/1 or /time_preferences/1.json
  def update
    respond_to do |format|
      if @time_preference.update(time_preference_params)
        format.html { redirect_to time_preference_url(@time_preference), notice: "Time preference was successfully updated." }
        format.json { render :show, status: :ok, location: @time_preference }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_preferences/1 or /time_preferences/1.json
  def destroy
    @time_preference.destroy!

    respond_to do |format|
      format.html { redirect_to time_preferences_url, notice: "Time preference was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_preference
      @time_preference = TimePreference.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_preference_params
      params.require(:time_preference).permit(:professor_id, :time_block_id, :priority)
    end
end

app/helpers/time_preferences_helper.rb
module TimePreferencesHelper
end

app/views/time_preferences/_form.html.erb
<%= form_with(model: time_preference) do |form| %>
  <% if time_preference.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(time_preference.errors.count, "error") %> prohibited this time_preference from being saved:</h2>

      <ul>
        <% time_preference.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :professor_id, style: "display: block" %>
    <%= form.text_field :professor_id %>
  </div>

  <div>
    <%= form.label :time_block_id, style: "display: block" %>
    <%= form.text_field :time_block_id %>
  </div>

  <div>
    <%= form.label :priority, style: "display: block" %>
    <%= form.number_field :priority %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/time_preferences/_time_preference.html.erb
<div id="<%= dom_id time_preference %>">
  <p>
    <strong>Professor:</strong>
    <%= time_preference.professor_id %>
  </p>

  <p>
    <strong>Time block:</strong>
    <%= time_preference.time_block_id %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= time_preference.priority %>
  </p>

</div>

app/views/time_preferences/edit.html.erb
<h1>Editing time preference</h1>

<%= render "form", time_preference: @time_preference %>

<br>

<div>
  <%= link_to "Show this time preference", @time_preference %> |
  <%= link_to "Back to time preferences", time_preferences_path %>
</div>

app/views/time_preferences/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Time preferences</h1>

<div id="time_preferences">
  <% @time_preferences.each do |time_preference| %>
    <%= render time_preference %>
    <p>
      <%= link_to "Show this time preference", time_preference %>
    </p>
  <% end %>
</div>

<%= link_to "New time preference", new_time_preference_path %>

app/views/time_preferences/new.html.erb
<h1>New time preference</h1>

<%= render "form", time_preference: @time_preference %>

<br>

<div>
  <%= link_to "Back to time preferences", time_preferences_path %>
</div>

app/views/time_preferences/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @time_preference %>

<div>
  <%= link_to "Edit this time preference", edit_time_preference_path(@time_preference) %> |
  <%= link_to "Back to time preferences", time_preferences_path %>

  <%= button_to "Destroy this time preference", @time_preference, method: :delete %>
</div>