config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sections
  resources :time_preferences
  resources :time_blocks
  resources :professors
  resources :course_preferences
  resources :courses
  resources :classrooms

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post "generate" => "static_pages#generate", as: :generate
  get "status" => "static_pages#status", as: :status

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  belongs_to :professor
  has_one :time_block, through: :start
  has_one :time_block, through: :end
  belongs_to :classroom
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]

  # GET /sections or /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to section_url(@section), notice: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to section_url(@section), notice: "Section was successfully updated." }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy!

    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id].split("_"))
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:course_id, :section_num, :professor_id, :start, :end, :classroom_id)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.label :section_num, style: "display: block" %>
    <%= form.number_field :section_num %>
  </div>

  <div>
    <%= form.label :professor_id, style: "display: block" %>
    <%= form.text_field :professor_id %>
  </div>

  <div>
    <%= form.label :start, style: "display: block" %>
    <%= form.number_field :start %>
  </div>

  <div>
    <%= form.label :end, style: "display: block" %>
    <%= form.number_field :end %>
  </div>

  <div>
    <%= form.label :classroom_id, style: "display: block" %>
    <%= form.text_field :classroom_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/_section.html.erb
<div id="<%= dom_id section %>">
  <p>
    <strong>Course:</strong>
    <%= section.course_id %>
  </p>

  <p>
    <strong>Section num:</strong>
    <%= section.section_num %>
  </p>

  <p>
    <strong>Professor:</strong>
    <%= section.professor_id %>
  </p>

  <p>
    <strong>Start:</strong>
    <%= section.start %>
  </p>

  <p>
    <strong>End:</strong>
    <%= section.end %>
  </p>

  <p>
    <strong>Classroom:</strong>
    <%= section.classroom_id %>
  </p>

</div>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Show this section", @section %> |
  <%= link_to "Back to sections", sections_path %>
</div>

app/views/sections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sections</h1>

<div id="sections">
  <% @sections.each do |section| %>
    <%= render section %>
    <p>
      <%= link_to "Show this section", section %>
    </p>
  <% end %>
</div>

<%= link_to "New section", new_section_path %>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Back to sections", sections_path %>
</div>

app/views/sections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @section %>

<div>
  <%= link_to "Edit this section", edit_section_path(@section) %> |
  <%= link_to "Back to sections", sections_path %>

  <%= button_to "Destroy this section", @section, method: :delete %>
</div>