config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sections
  resources :time_preferences
  resources :time_blocks
  resources :professors
  resources :course_preferences
  resources :courses
  resources :classrooms

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post "generate" => "static_pages#generate", as: :generate
  get "status" => "static_pages#status", as: :status

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :sections, dependent: :destroy
  has_many :course_preferences, dependent: :destroy
  has_many :time_preferences, dependent: :destroy
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: %i[ show edit update destroy ]

  # GET /professors or /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1 or /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors or /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to professor_url(@professor), notice: "Professor was successfully created." }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1 or /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to professor_url(@professor), notice: "Professor was successfully updated." }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1 or /professors/1.json
  def destroy
    @professor.destroy!

    respond_to do |format|
      format.html { redirect_to professors_url, notice: "Professor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def professor_params
      params.require(:professor).permit(:name)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor) do |form| %>
  <% if professor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
        <% professor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/_professor.html.erb
<div id="<%= dom_id professor %>">
  <p>
    <strong>Name:</strong>
    <%= professor.name %>
  </p>

</div>

app/views/professors/edit.html.erb
<h1>Editing professor</h1>

<%= render "form", professor: @professor %>

<br>

<div>
  <%= link_to "Show this professor", @professor %> |
  <%= link_to "Back to professors", professors_path %>
</div>

app/views/professors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Professors</h1>

<div id="professors">
  <% @professors.each do |professor| %>
    <%= render professor %>
    <p>
      <%= link_to "Show this professor", professor %>
    </p>
  <% end %>
</div>

<%= link_to "New professor", new_professor_path %>

app/views/professors/new.html.erb
<h1>New professor</h1>

<%= render "form", professor: @professor %>

<br>

<div>
  <%= link_to "Back to professors", professors_path %>
</div>

app/views/professors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @professor %>

<div>
  <%= link_to "Edit this professor", edit_professor_path(@professor) %> |
  <%= link_to "Back to professors", professors_path %>

  <%= button_to "Destroy this professor", @professor, method: :delete %>
</div>